---
title: Tom o'Keefe
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: false
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: projects
  values:
    is-front: 
    image: 
    vimeo: 
    youtube: 
    director: 
    production-company: 
    awards: 
    layout: project
exclude:
- config.codekit3
- README*
- LICENSE*
- CHANGELOG*
- node_modules
- ".gitignore"
- bower_components
- assets/scss
plugins:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
- jekyll/imgix
permalink: pretty
markdown: kramdown
kramdown:
  auto_ids: false
highlighter: rouge
compress_html:
  comments:
  - "<!-- "
  - " -->"
  blanklines: true
  profile: false
encoding: utf-8
url: http://tomokeefe.co.uk
description: London-based Director of Photography for film, television, and music.
job-title: Director of Photography
reel: 256575394
company: Tom o'Keefe
email: info@tomokeefe.co.uk
google_site_verification: HbAqicGmzVymBcbYJZ73TmDI19qJj3h-baQc4Grywgc
analytics: UA-91433652-1
logo: "/assets/img/logo.svg"
per_page: 12
date_format: "%b %d, %Y"
future: true
